### ISSUE TITLE
mkdocs build 出现错误

### ISSUE THREAD

**Issue by ridethepig** [LearnOpenGL-CN/LearnOpenGL-CN#91]
`mkdocs build` 在new-theme分支下会出现如下错误，但是master并不会出错

> proto@DESKTOP-3U70OFU MINGW64 ~/Documents/Code/repos/LearnOpenGL-CN (new-theme)
$ mkdocs build
WARNING -  Config value: 'theme_dir'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs.
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\Users\proto\Documents\Code\repos\LearnOpenGL-CN\site
ERROR   -  Error building page index.md
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\mkdocs\__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "c:\program files\python36\lib\site-packages\mkdocs\commands\build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "c:\program files\python36\lib\site-packages\mkdocs\commands\build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "c:\program files\python36\lib\site-packages\mkdocs\commands\build.py", line 150, in _build_page
    template = env.get_template('main.html')
  File "c:\program files\python36\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\program files\python36\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\program files\python36\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\program files\python36\lib\site-packages\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.html

**Comment by Meow-J** [comment]
可以看一下这里面的所使用的版本，新版本的mkdocs改的东西有点多会不兼容：

https://github.com/LearnOpenGL-CN/LearnOpenGL-CN/blob/new-theme/.travis.yml
